name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Flask App to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Stop any running app
            pkill -f app.py || true

            # Prepare deployment directory
            rm -rf ~/flaskapp
            mkdir -p ~/flaskapp
            cd ~/flaskapp

            # Clone updated code
            git clone https://github.com/${{ github.repository }} . || true

            # Install Flask if not already installed
            pip3 install --user flask

            # Launch the Flask app in the background properly
            (nohup python3 app.py > out.log 2>&1 < /dev/null &) &
