name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Kill the specific app process if running
            pkill -f "python3 app.py" || echo "No app.py process found"

            # Clean and prepare deployment directory
            DEPLOY_DIR="flaskapp"
            rm -rf $DEPLOY_DIR
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # Clone the repository
            if ! git clone https://github.com/${{ github.repository }} .; then
              echo "Failed to clone repository" >&2
              exit 1
            fi

            # Install dependencies
            if ! pip3 install --user flask; then
              echo "Failed to install Flask" >&2
              exit 1
            fi

            # Start the application
            nohup python3 app.py > out.log 2>&1 < /dev/null &
